---
profiles:
  minimal: [base, cli, shell, neovim]
  server:  [base, cli, shell, neovim, ssh, terminal, nerdfonts, devtools, firewall]
  desktop: [base, cli, shell, neovim, ssh, terminal, wayland, nerdfonts, devtools]
  gaming:  [base, cli, shell, neovim, ssh, terminal, wayland, nerdfonts, devtools, gaming]
  htpc:    [base, cli, shell, neovim, ssh, terminal, wayland, nerdfonts, hyprland, noctalia, media]
  laptop:  [base, cli, shell, neovim, ssh, terminal, wayland, nerdfonts, devtools, laptop]
