---
nerd_fonts:
  - JetBrainsMono

nerd_fonts_version: "v3.4.0"

nerd_fonts_base_url: >-
  {{ 'https://github.com/ryanoasis/nerd-fonts/releases/latest/download'
     if nerd_fonts_version == 'latest'
     else 'https://github.com/ryanoasis/nerd-fonts/releases/download/' ~ nerd_fonts_version }}

nerd_fonts_dir: "{{ ansible_facts['env']['HOME'] }}/.local/share/fonts"
