---
hyprland_config_dir: "{{ ansible_facts['env']['HOME'] }}/.config/hypr"

hyprland_link_files:
  - hyprland.lua
  - env.lua
  - settings.lua
  - devices.lua
  - keybinds.lua
  - hover_close.lua
  - monitors.lua
  - animations.lua
  - rules.lua
  - autostart.lua
  - vars.lua
