config_version = 12

[audio]
enable_sounds = true

[bar.default]
background_opacity = 0.9499999787658453
center = [ "clock", "weather" ]
end = [ "media", "group:g1", "tray", "clipboard", "bluetooth", "network", "volume", "session" ]
font_weight = 600
margin_ends = 0
scale = 1.2500000111758709
start = [ "workspaces" ]

    [bar.default.dead_zone.actions]
    left = "panel-toggle control-center home"
    right = "panel-toggle control-center settings"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = false
    fill = "surface_variant"
    id = "g1"
    members = [ "network_rx", "ram", "sysmon" ]
    opacity = 1.0
    padding = 6.0

[dock]
enabled = true
icon_size = 52
launcher_icon = "search"
launcher_position = "start"
pinned = [ "org.kde.dolphin", "firefox", "steam" ]
reserve_space = false
show_dots = true
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
enabled = [ "yuuto/arch-updater" ]

[shell]
settings_window_translucent = true
telemetry_enabled = true

    [shell.launcher.providers.calculator]
    prefix = "="

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "systemctl reboot --firmware-setup"
    countdown_seconds = 0.0
    enabled = true
    glyph = "cpu"
    label = "Reboot to BIOS"
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "destructive"

[theme]
builtin = "Tokyo-Night"
community_palette = "Neon Surf"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "qt", "starship" ]

[wallpaper.default]
path = "/home/bnb/Pictures/Wallpapers/wallhaven-8gjxoy.png"

[wallpaper.last]
path = "/home/bnb/Pictures/Wallpapers/wallhaven-8gjxoy.png"

[wallpaper.monitors.HDMI-A-1]
path = "/home/bnb/Pictures/Wallpapers/wallhaven-8gjxoy.png"

[widget.clock]
timezone = "Europe/London"

[widget.control-center]
glyph = "navigation"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.network_rx]
capsule = true
network_speed_compact = true
show_glyph = false
show_value = false
visualization = "graph"

    [widget.network_rx.actions]
    left = "panel-toggle control-center network"

[widget.tray]
drawer = true
hidden = [ "clipboard" ]

[widget.volume]
show_label = false

[widget.weather]
show_condition = false